# Generated by Django 5.2.8 on 2025-12-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='subdesc',
            field=models.TextField(default=None, verbose_name='Доп. описание', null=True),
            preserve_default=False,
        ),
    ]
