# Generated by Django 5.2.8 on 2025-12-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quest_subdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='desc',
            field=models.TextField(default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='subdesc',
            field=models.TextField(default=None, null=True, verbose_name='Доп. описание'),
        ),
    ]
